src/mizokoshi_yohei/beans/Comment.java
package mizokoshi_yohei.beans;

import java.io.Serializable;
import java.util.Date;


public class Comment implements Serializable {
    private static final long serialVersionUID = 1L;

    
    private int id;
    private String comment;
    private String name;
    private int user_id;
    private int Message_id;
    private Date createdDate;
    private Date updatedDate;
   

    public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public int getUser_id() {
		return user_id;
	}
	public void setUser_id(int user_id) {
		this.user_id = user_id;
	}
	public int getMessage_id() {
		return Message_id;
	}
	public void setMessage_id(int Message_id) {
		this.Message_id = Message_id;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}

src/mizokoshi_yohei/beans/Message.java
package mizokoshi_yohei.beans;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
    //private static final long serialVersionUID = 1L;

    private int id;
    private int user_id;
    private String name;
    private String title;
    private String text;
    private String category;
    private Date createdDate;
    private Date updatedDate;
    
   
    
    
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getUserId() {
		return user_id;
	}
	public void setUserId(int user_id) {
		this.user_id = user_id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}

src/mizokoshi_yohei/controller/HomeServlet.java
package mizokoshi_yohei.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import mizokoshi_yohei.beans.Message;
import mizokoshi_yohei.beans.User;
import mizokoshi_yohei.beans.UserComment;
import mizokoshi_yohei.service.CommentService;
import mizokoshi_yohei.service.MessageService;


@WebServlet(urlPatterns = { "/index.jsp" })
public class HomeServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        User user = (User) request.getSession().getAttribute("loginUser");
        boolean isShowMessageForm;
        if (user != null) {
            isShowMessageForm = true;
        } else {
            isShowMessageForm = false;
        }

        List<Message> messages = new MessageService().getMessage();
        List<UserComment> comments = new CommentService().getComment();

        //System.out.println(messages.getUserId());
        request.setAttribute("messages", messages);
        request.setAttribute("comments", comments);
        request.setAttribute("isShowMessageForm", isShowMessageForm);
        


        request.getRequestDispatcher("/Home.jsp").forward(request, response);
    
    
    }
}

src/mizokoshi_yohei/controller/LoginServlet.java
package mizokoshi_yohei.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import mizokoshi_yohei.beans.User;
import mizokoshi_yohei.service.LoginService;


@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
	@Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        String loginId = request.getParameter("loginId");
        String password = request.getParameter("password");

        LoginService loginService = new LoginService();
        User user = loginService.login(loginId, password);

        HttpSession session = request.getSession();
        if (user != null) {

            session.setAttribute("loginUser", user);
            response.sendRedirect("./");
        } else {

            List<String> messages = new ArrayList<String>();
            messages.add("ログインに失敗しました。");
            session.setAttribute("errorMessages", messages);
            response.sendRedirect("login");
        }
    }

}

src/mizokoshi_yohei/controller/NewTreadServlet.java
package mizokoshi_yohei.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import mizokoshi_yohei.beans.Message;
import mizokoshi_yohei.beans.User;
import mizokoshi_yohei.service.MessageService;

@WebServlet(urlPatterns = { "/newTread" })
public class NewTreadServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("NewTread.jsp").forward(request, response);
    }
    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        HttpSession session = request.getSession();

        List<String> messages = new ArrayList<String>();

        if (isValid(request, messages) == true) {

            User user = (User) session.getAttribute("loginUser");

            Message message = new Message();
            message.setTitle(request.getParameter("title"));
            message.setText(request.getParameter("text"));
            message.setCategory(request.getParameter("category"));
            message.setUserId(user.getId());

            new MessageService().register(message);

            response.sendRedirect("Home");
        } else {
            session.setAttribute("errorMessages", messages);
            response.sendRedirect("newTread");
        }
    }

    private boolean isValid(HttpServletRequest request, List<String> messages) {

        String title = request.getParameter("title");
        String text = request.getParameter("text");
        String category = request.getParameter("category");

        if (StringUtils.isEmpty(title) == true) {
            messages.add("件名を入力してください");
        }
        if (StringUtils.isEmpty(title) != true && title.length() > 30) {
        	messages.add("件名は30文字以下で入力してください");
        }
        if (StringUtils.isEmpty(text) == true) {
            messages.add("本文を入力してください");
        }
        if (StringUtils.isEmpty(text) != true && 1000 < text.length()) {
            messages.add("本文は1000文字以下で入力してください");
        }
        if (StringUtils.isEmpty(category) == true) {
            messages.add("カテゴリーを入力してください");
        }
        if (StringUtils.isEmpty(title) != true && category.length() > 10) {
            messages.add("カテゴリー名は10字以下で入力してください");
        }
        if (messages.size() == 0) {
            return true;
        } else {
            return false;
        }
    }

}

src/mizokoshi_yohei/controller/SignUpServlet.java
package mizokoshi_yohei.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import mizokoshi_yohei.beans.User;
import mizokoshi_yohei.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("SignUp.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        List<String> messages = new ArrayList<String>();

        HttpSession session = request.getSession();
        if (isValid(request, messages) == true) {

            User user = new User();
            user.setName(request.getParameter("name"));
            user.setLoginId(request.getParameter("loginId"));
            user.setPassword(request.getParameter("password"));
            user.setBrunches(request.getParameter("brunches"));
            user.setPosition(request.getParameter("position"));

            new UserService().register(user);

            response.sendRedirect("usermanagement");
        } else {
            session.setAttribute("errorMessages", messages);
            response.sendRedirect("signup");
        }
    }

    private boolean isValid(HttpServletRequest request, List<String> messages) {
        String name = request.getParameter("name");
        String loginId = request.getParameter("loginId");
        String password = request.getParameter("password");
        String brunches = request.getParameter("brunches");
        String position = request.getParameter("position");
        
        

        if (StringUtils.isEmpty(name) == true) {
            messages.add("名前を入力してください");
        }
        if (StringUtils.isEmpty(name) != true && !(name.length() <= 10)) {
        	messages.add("名称は10文字以下にしてください");
        }
        if (StringUtils.isEmpty(loginId) == true) {
            messages.add("ログインIDを入力してください");
        }
        if (StringUtils.isEmpty(loginId) != true && !(loginId.matches("^[0-9a-z]+$") && loginId.length() >= 6 && loginId.length() <= 20)) {
        	messages.add("半角英数字6文字以上20文字以内で入力してください");
        }
        if (StringUtils.isEmpty(password) == true) {
            messages.add("パスワードを入力してください");
        }
        if (StringUtils.isEmpty(password) != true && !(password.length() >= 6 && password.length() <= 20)) {
        	messages.add("記号を含む全ての半角文字で6文字以上20文字以下で入力してください");
        }
        if (StringUtils.isEmpty(brunches) == true) {
            messages.add("支店名を入力してください");
        }
        if (StringUtils.isEmpty(position) == true) {
            messages.add("部署・役職を入力してください");
        }
        // TODO アカウントが既に利用されていないか、メールアドレスが既に登録されていないかなどの確認も必要
        if (messages.size() == 0) {
            return true;
        } else {
            return false;
        }
    }

}

src/mizokoshi_yohei/controller/UserManagementServlet.java
package mizokoshi_yohei.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(urlPatterns = { "/usermanagement" })
public class UserManagementServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    
   
	@Override
	protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("UserManagement.jsp").forward(request, response);
    }
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}

WebContent/Home.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>HOME</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">
		
		<form method="post" action="SearchCategory">
        <div>検索したいカテゴリーを入力してください</div>
        <div>
            <input type="text" name="name" maxlength="20" size="20">
        </div>
         <input type="submit" value="検索">
    </form>
			
			<div class="messages">
			    <c:forEach items="${messages}" var="message">
			    
			            <div class="message">
			                <div class="account-name">
			                    <span class="name"><c:out value="${message.name}" /></span>
			                </div>
			                <div class="title"><c:out value="${message.title}" /></div>
			                <div class="text"><c:out value="${message.text}" /></div>
			                <div class="category"><c:out value="${message.category }" /></div>
			                <div class="date"><fmt:formatDate value="${message.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
			                
			            </div>
			        
 			        <c:if test="${loginUser.id == message.userId}">
 			        <form action="messageDelete" method="post">
			        <input type="submit" value="削除">
			        
			        </form>
			        </c:if>
			        
			        <c:forEach items="${comments}" var="comment" >
			        
			        <c:if test="${message.id == comment.message_id }">
			             <div class="comment">
			                 <div class="comment"><c:out value="${comment.comment}" /></div>
			                 <span class="name"><c:out value="${comment.name}" /></span>
			                 <div class="date"><fmt:formatDate value="${comment.created_date}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
			             </div>
			        </c:if>
			     </c:forEach>
			       
			     
		<div class="form-area">
				<c:if test="${ isShowMessageForm }">
					<form action="newComment" method="post">
						コメント<br />
						<textarea name="comment" cols="100" rows="5" class="tweet-box"></textarea>
						<input  type="hidden" name="message_id"value="${message.id }"/>>
						<br />
						<input type="submit" value="コメントする">
					</form>
				</c:if>
			</div>
			
			<c:if test="${ not empty errorComment }">
			<div class="errorComment">
				<ul>
					<c:forEach items="${errorComment}" var="comments">
						<li><c:out value="${comments}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorComment" scope="session" />
		</c:if>
		</c:forEach>
			                <div class="date"><fmt:formatDate value="${message.created_date}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
			            </div>
			    
			</div>
			
			<a href="newTread">新規投稿</a>
			<div class="copylight"> Copyright(c)mizokoshi_yohei</div>
		
	</body>
</html>

WebContent/NewTread.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>新規投稿</title>

</head>
<body>
<c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>
<div class="form-area">
    
        <form action="newTread" method="post">
            <br /> <label for="title">件名：</label><input type="text" name="title" id="title"><br />
            <br /> <label for="text">本文</label><textarea name="text" cols="100" rows="5" class="tweet-box" id="text"></textarea>
            <br />
            <br /> <label for="category">カテゴリー</label> <input type="text" name="category" id="category" />
            <a href="newTread"><input type="submit" value="投稿" /></a>
        </form>
    
  </div>
  <div class="copylight"> Copyright(c)mizokoshi_yohei</div>
</body>
</html>

WebContent/SignUp.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>ユーザー登録</title>
    <link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>
            <form action="signup" method="post">
                <br /> <label for="name">名前</label> <input name="name" id="name" />
                <br /> <label for="loginId">ログインID</label> <input name="loginId" id="loginId" /> 
                <br /> <label for="password">パスワード</label> <input name="password" type="password" id="password" /> 
                <br /> <label for="brunches">支店</label> <input type="number" min="1" name="brunches" id="brunches" />
                <br /> <label for="position">部署・役職</label> <input type="number" min="1" name="position" id="position" />
                
                
                
                <br /> <input type="submit" value="登録" /> <br /> <a href="./">戻る</a>
            </form>
            <div class="copyright">Copyright(c)mizokoshi_yohei</div>
        </div>
    </body>
</html>

WebContent/UserManagement.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ユーザー管理</title>
</head>
<body>
ｊかｆしおえｗｊ
</body>
</html>

WebContent/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Login page</title>
</head>
<body>
	<div class="main-contents">

		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>

		<form action="login" method="post"><br /> 
		  <label for="loginId">ログインID</label> 
		  <input name="loginId" id="loginId" /> <br /> 
		  <label for="password">パスワード</label> 
		  <input name="password" type="password" id="password" /> <br />
		  <input type="submit" value="ログイン" /> <br />
		  



		</form>
		<div class="copylight">Copyright(c)mizokoshi_yohei</div>
	</div>

</body>
</html>